# Unit-1 Pandas
**Instructions:** Write your Python code in each code cell below. Save and upload when done.

## Dataset
Run the cell below to load the dataset. All questions below use this dataset.

In [3]:
import pandas as pd

data = {
    'StudentID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivy', 'Jack'],
    'MathScore': [85, 92, 78, 88, 95, 72, 81, 90, 83, 76],
    'ScienceScore': [90, 88, 82, 91, 93, 75, 80, 89, 84, 78],
    'AttendancePercentage': [95.5, 98.2, 90.0, 96.1, 99.0, 88.5, 92.3, 97.0, 93.8, 89.5]
}
df = pd.DataFrame(data)

## Topic: Series
A Pandas Series is a one-dimensional labeled array capable of holding any type of data. It's like a column in a table or a single list with an index.

**Question 1:** From the provided student DataFrame, create a Pandas Series containing only the 'Name' column. What is the data type of this Series?

In [4]:
name_series = df['Name']
print(name_series)
print("Series dtype:", name_series.dtype)


0      Alice
1        Bob
2    Charlie
3      David
4        Eve
5      Frank
6      Grace
7      Heidi
8        Ivy
9       Jack
Name: Name, dtype: str
Series dtype: str


## Topic: Series
You can perform various operations on Series, such as calculating statistics or accessing elements. Understanding indexing is key to manipulating Series effectively.

**Question 2:** Create a Pandas Series from the 'MathScore' column of the student DataFrame. Calculate the average MathScore using this Series. What is the average MathScore?

In [5]:
math_series = df['MathScore']
average_math = math_series.mean()
print("Average MathScore:", average_math)


Average MathScore: 84.0


## Topic: Series
Series allow for efficient selection of data based on their index. You can retrieve single elements, slices, or elements based on conditional criteria.

**Question 3:** Using the 'ScienceScore' column as a Series, select the ScienceScore for the student at index 3 (David). What is this score?

In [6]:
science_series = df['ScienceScore']
print("ScienceScore at index 3:", science_series.loc[3])


ScienceScore at index 3: 91


## Topic: Series
Operations like sorting and filtering can be applied to Series to organize and extract specific information.

**Question 4:** Create a Series from the 'AttendancePercentage' column. Sort this Series in descending order. What is the highest attendance percentage?

In [7]:
attendance_series = df['AttendancePercentage']
sorted_attendance = attendance_series.sort_values(ascending=False)
print(sorted_attendance)
print("Highest attendance percentage:", sorted_attendance.iloc[0])


4    99.0
1    98.2
7    97.0
3    96.1
0    95.5
8    93.8
6    92.3
2    90.0
9    89.5
5    88.5
Name: AttendancePercentage, dtype: float64
Highest attendance percentage: 99.0


## Topic: Series
Series are fundamental building blocks in Pandas, and many DataFrame operations are built upon Series operations.

**Question 5:** Create a Series from the 'StudentID' column. How many unique StudentIDs are there in this Series?

In [8]:
student_id_series = df['StudentID']
print("Unique StudentIDs:", student_id_series.nunique())


Unique StudentIDs: 10


## Topic: DataFrame
A Pandas DataFrame is a two-dimensional labeled data structure with columns of potentially different types. It's like a spreadsheet or a SQL table.

**Question 6:** Using the provided student data, create a Pandas DataFrame. Display the first 5 rows of this DataFrame.

In [9]:
student_df = pd.DataFrame(data)
student_df.head()


,StudentID,Name,MathScore,ScienceScore,AttendancePercentage
0,101,Alice,85,90,95.5
1,102,Bob,92,88,98.2
2,103,Charlie,78,82,90.0
3,104,David,88,91,96.1
4,105,Eve,95,93,99.0


## Topic: DataFrame
You can select specific columns from a DataFrame to work with. This is a fundamental operation for focusing on relevant data.

**Question 7:** From the student DataFrame, select only the 'Name' and 'MathScore' columns. Display the resulting DataFrame.

In [10]:
selected_columns = df[['Name', 'MathScore']]
selected_columns


,Name,MathScore
0,Alice,85
1,Bob,92
2,Charlie,78
3,David,88
4,Eve,95
5,Frank,72
6,Grace,81
7,Heidi,90
8,Ivy,83
9,Jack,76


## Topic: DataFrame
DataFrames allow for row-based selection using boolean indexing, enabling you to filter data based on conditions.

**Question 8:** Filter the student DataFrame to show only students who scored above 90 in Math. Display the 'Name' and 'MathScore' for these students.

In [11]:
high_math_scores = df[df['MathScore'] > 90][['Name', 'MathScore']]
high_math_scores


,Name,MathScore
1,Bob,92
4,Eve,95


## Topic: DataFrame
You can add new columns to a DataFrame, often derived from existing columns or external data.

**Question 9:** Add a new column called 'TotalScore' to the student DataFrame, which is the sum of 'MathScore' and 'ScienceScore'. Display the DataFrame with the new column.

In [12]:
df['TotalScore'] = df['MathScore'] + df['ScienceScore']
df


,StudentID,Name,MathScore,ScienceScore,AttendancePercentage,TotalScore
0,101,Alice,85,90,95.5,175
1,102,Bob,92,88,98.2,180
2,103,Charlie,78,82,90.0,160
3,104,David,88,91,96.1,179
4,105,Eve,95,93,99.0,188
5,106,Frank,72,75,88.5,147
6,107,Grace,81,80,92.3,161
7,108,Heidi,90,89,97.0,179
8,109,Ivy,83,84,93.8,167
9,110,Jack,76,78,89.5,154


## Topic: DataFrame
DataFrames provide methods to inspect their structure, such as checking data types and non-null counts.

**Question 10:** Get information about the student DataFrame, including the data types of each column and the number of non-null values. What are the data types of 'MathScore' and 'AttendancePercentage'?

In [13]:
df.info()
print("MathScore dtype:", df['MathScore'].dtype)
print("AttendancePercentage dtype:", df['AttendancePercentage'].dtype)


<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   StudentID             10 non-null     int64  
 1   Name                  10 non-null     str    
 2   MathScore             10 non-null     int64  
 3   ScienceScore          10 non-null     int64  
 4   AttendancePercentage  10 non-null     float64
 5   TotalScore            10 non-null     int64  
dtypes: float64(1), int64(4), str(1)
memory usage: 612.0 bytes
MathScore dtype: int64
AttendancePercentage dtype: float64


## Topic: Cleaning Data
Data cleaning involves handling missing values, correcting errors, and dealing with inconsistencies in your dataset. This is a crucial step before analysis.

**Question 11:** Imagine a new student was added with missing 'ScienceScore' and 'AttendancePercentage'. Create a new DataFrame with this additional row (StudentID: 111, Name: 'Kane', MathScore: 70). How would you represent the missing values in the 'ScienceScore' and 'AttendancePercentage' columns, and what function would you use to check for them?

In [14]:
new_student = {
    'StudentID': 111,
    'Name': 'Kane',
    'MathScore': 70,
    'ScienceScore': float('nan'),
    'AttendancePercentage': float('nan')
}
df_with_missing = pd.concat([df, pd.DataFrame([new_student])], ignore_index=True)
print(df_with_missing.tail())
print(df_with_missing[['ScienceScore', 'AttendancePercentage']].isna().tail())


    StudentID   Name  MathScore  ScienceScore  AttendancePercentage  \
6         107  Grace         81          80.0                  92.3   
7         108  Heidi         90          89.0                  97.0   
8         109    Ivy         83          84.0                  93.8   
9         110   Jack         76          78.0                  89.5   
10        111   Kane         70           NaN                   NaN   

    TotalScore  
6        161.0  
7        179.0  
8        167.0  
9        154.0  
10         NaN  
    ScienceScore  AttendancePercentage
6          False                 False
7          False                 False
8          False                 False
9          False                 False
10          True                  True


## Topic: Cleaning Data
Missing data can be handled by filling them with a specific value (e.g., mean, median) or by removing rows/columns with missing values.

**Question 12:** For the student DataFrame, assume 'AttendancePercentage' has some missing values represented as NaN. If you wanted to fill these missing values with the average attendance percentage of all students, what Pandas function would you use, and what value would you pass to it?

In [15]:
average_attendance = df_with_missing['AttendancePercentage'].mean()
df_filled = df_with_missing.copy()
df_filled['AttendancePercentage'] = df_filled['AttendancePercentage'].fillna(average_attendance)
print("Average attendance used for fillna:", average_attendance)
print(df_filled.tail())


Average attendance used for fillna: 93.98999999999998
    StudentID   Name  MathScore  ScienceScore  AttendancePercentage  \
6         107  Grace         81          80.0                 92.30   
7         108  Heidi         90          89.0                 97.00   
8         109    Ivy         83          84.0                 93.80   
9         110   Jack         76          78.0                 89.50   
10        111   Kane         70           NaN                 93.99   

    TotalScore  
6        161.0  
7        179.0  
8        167.0  
9        154.0  
10         NaN  


## Topic: Cleaning Data
Data types can sometimes be incorrect, leading to issues in analysis. Converting data types is a common cleaning task.

**Question 13:** If the 'AttendancePercentage' column was initially read as an object (string) type due to a typo like '95.5%', how would you convert it to a numeric (float) type? What function would you use?

In [16]:
df['AttendancePercentage'] = pd.to_numeric(
    df['AttendancePercentage'].astype(str).str.rstrip('%'),
    errors='coerce'
)
print(df['AttendancePercentage'])
print("Converted dtype:", df['AttendancePercentage'].dtype)


0    95.5
1    98.2
2    90.0
3    96.1
4    99.0
5    88.5
6    92.3
7    97.0
8    93.8
9    89.5
Name: AttendancePercentage, dtype: float64
Converted dtype: float64


## Topic: Cleaning Data
Identifying and removing duplicate records is essential to ensure data integrity and prevent biased analysis.

**Question 14:** Suppose the student DataFrame accidentally had a duplicate row for 'Alice' (StudentID 101). How would you identify this duplicate row and then remove it to keep only the first occurrence?

In [17]:
df_with_duplicate = pd.concat([df, df[df['StudentID'] == 101]], ignore_index=True)
duplicate_rows = df_with_duplicate[df_with_duplicate.duplicated(subset=['StudentID', 'Name'], keep=False)]
print("Duplicate rows:")
print(duplicate_rows)
df_no_duplicates = df_with_duplicate.drop_duplicates(subset=['StudentID', 'Name'], keep='first')
print("\nAfter removing duplicates:")
print(df_no_duplicates)


Duplicate rows:
    StudentID   Name  MathScore  ScienceScore  AttendancePercentage  \
0         101  Alice         85            90                  95.5   
10        101  Alice         85            90                  95.5   

    TotalScore  
0          175  
10         175  

After removing duplicates:
   StudentID     Name  MathScore  ScienceScore  AttendancePercentage  \
0        101    Alice         85            90                  95.5   
1        102      Bob         92            88                  98.2   
2        103  Charlie         78            82                  90.0   
3        104    David         88            91                  96.1   
4        105      Eve         95            93                  99.0   
5        106    Frank         72            75                  88.5   
6        107    Grace         81            80                  92.3   
7        108    Heidi         90            89                  97.0   
8        109      Ivy         83           

## Topic: Cleaning Data
Sometimes, data might be stored in an inconsistent format (e.g., 'USA' vs 'United States'). Standardizing these values is part of cleaning.

**Question 15:** If there was a column 'Grade' in the student DataFrame with values like 'A', 'a', and 'A+', how would you standardize these to a single consistent format like 'A' for analysis?

In [18]:
df_grades = df.copy()
df_grades['Grade'] = ['A', 'a', 'A+', 'B', 'b', 'C', 'A', 'a+', 'B+', 'c']
df_grades['Grade'] = df_grades['Grade'].str.strip().str.upper().replace({'A+': 'A'})
df_grades['Grade'] = df_grades['Grade'].str.strip().str.upper().replace({'B+': 'B'})
print(df_grades[['Name', 'Grade']])


      Name Grade
0    Alice     A
1      Bob     A
2  Charlie     A
3    David     B
4      Eve     B
5    Frank     C
6    Grace     A
7    Heidi     A
8      Ivy     B
9     Jack     C


## Topic: Data Aggregation & Transformation
Data aggregation involves summarizing data using functions like sum, mean, count, min, and max. This is often done after grouping data by certain criteria.

**Question 16:** Using the student DataFrame, calculate the average 'MathScore' for all students. What is this average score?

In [19]:
avg_mathscore = df['MathScore'].mean()
print("Average MathScore:", avg_mathscore)


Average MathScore: 84.0


## Topic: Data Aggregation & Transformation
Grouping data allows you to perform aggregations on subsets of your data. For example, you might group by a category and then calculate statistics for each category.

**Question 17:** If you had a 'Subject' column in the student DataFrame (e.g., 'Math', 'Science'), how would you group the DataFrame by 'Subject' and then calculate the average score for each subject?

In [20]:
df

,StudentID,Name,MathScore,ScienceScore,AttendancePercentage,TotalScore
0,101,Alice,85,90,95.5,175
1,102,Bob,92,88,98.2,180
2,103,Charlie,78,82,90.0,160
3,104,David,88,91,96.1,179
4,105,Eve,95,93,99.0,188
5,106,Frank,72,75,88.5,147
6,107,Grace,81,80,92.3,161
7,108,Heidi,90,89,97.0,179
8,109,Ivy,83,84,93.8,167
9,110,Jack,76,78,89.5,154


## Topic: Data Aggregation & Transformation
Transformation involves changing the structure or values within your data. This can include applying functions to columns or creating new derived columns.

**Question 18:** Create a new column called 'MathGrade' in the student DataFrame. Assign 'A' if 'MathScore' is >= 90, 'B' if between 80 and 89, and 'C' otherwise. Display the DataFrame with this new column.

In [21]:
df['MathGrade'] = 'C'
df.loc[df['MathScore'].between(80, 89), 'MathGrade'] = 'B'
df.loc[df['MathScore'] >= 90, 'MathGrade'] = 'A'
print(df[['Name', 'MathScore', 'MathGrade']])


      Name  MathScore MathGrade
0    Alice         85         B
1      Bob         92         A
2  Charlie         78         C
3    David         88         B
4      Eve         95         A
5    Frank         72         C
6    Grace         81         B
7    Heidi         90         A
8      Ivy         83         B
9     Jack         76         C


## Topic: Data Aggregation & Transformation
You can apply multiple aggregation functions to different columns simultaneously using the `.agg()` method.

**Question 19:** Using the student DataFrame, calculate the maximum 'ScienceScore' and the minimum 'AttendancePercentage' in a single operation. Display both results.

In [22]:
summary_stats = df[['ScienceScore', 'AttendancePercentage']].agg({
    'ScienceScore': 'max',
    'AttendancePercentage': 'min'
})
print(summary_stats)


ScienceScore            93.0
AttendancePercentage    88.5
dtype: float64


## Topic: Data Aggregation & Transformation
Reshaping data is a powerful transformation technique used to change the layout of your DataFrame for different analytical needs.

**Question 20:** If you wanted to transform the student DataFrame so that each student has one row and columns for 'MathScore' and 'ScienceScore' are represented as rows under a 'ScoreType' column, what Pandas function would you use?

In [23]:
long_format = pd.concat([
    df[['StudentID', 'Name', 'MathScore']].rename(columns={'MathScore': 'Score'}).assign(ScoreType='MathScore'),
    df[['StudentID', 'Name', 'ScienceScore']].rename(columns={'ScienceScore': 'Score'}).assign(ScoreType='ScienceScore')
], ignore_index=True)[['StudentID', 'Name', 'ScoreType', 'Score']]
print(long_format)


    StudentID     Name     ScoreType  Score
0         101    Alice     MathScore     85
1         102      Bob     MathScore     92
2         103  Charlie     MathScore     78
3         104    David     MathScore     88
4         105      Eve     MathScore     95
5         106    Frank     MathScore     72
6         107    Grace     MathScore     81
7         108    Heidi     MathScore     90
8         109      Ivy     MathScore     83
9         110     Jack     MathScore     76
10        101    Alice  ScienceScore     90
11        102      Bob  ScienceScore     88
12        103  Charlie  ScienceScore     82
13        104    David  ScienceScore     91
14        105      Eve  ScienceScore     93
15        106    Frank  ScienceScore     75
16        107    Grace  ScienceScore     80
17        108    Heidi  ScienceScore     89
18        109      Ivy  ScienceScore     84
19        110     Jack  ScienceScore     78
